name: Automatic PR Merging

on:
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
  #  paths-ignore: [".vscode/**", "README.md", ".*"]
  workflow_dispatch:

jobs:
    AutoMerge:
        name: Merge pull request
        runs-on: psl-app-vm3
        if: github.base_ref == 'master' && github.actor == 'dependabot[bot]'
        steps:
              - name: Merge
                uses: actions/github-script@0.2.0
                with:
                    script: |
                        github.pullRequests.merge({
                            owner: context.payload.repository.owner.login,
                            repo: context.payload.repository.name,
                            pull_number: context.payload.pull_request.number
                        })
                    github-token: ${{ github.token }}
